version: '2'

networks:
  app-tier:
    driver: bridge

services:
  Etcd:
    image: quay.io/coreos/etcd:v3.6.8
    # environment:
    #   - ALLOW_NONE_AUTHENTICATION=yes
    #   - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    command: | 
      etcd 
      -name etcd0 
      -advertise-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 
      -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 
      -initial-advertise-peer-urls http://0.0.0.0:2380 
      -listen-peer-urls http://0.0.0.0:2380 
      -initial-cluster-token etcd-cluster-1 
      -initial-cluster etcd0=http://0.0.0.0:2380 
      -initial-cluster-state new
    ports:
      - 2379:2379
      - 2380:2380
